rewards: fix unused import to fix CI (#670)
#### Problem
Looks like #664 broke master:
```
error: unused import: `epoch_stakes::BLSPubkeyToRankMap`
 --> runtime/src/validated_reward_certificate.rs:2:25
  |
2 |     crate::{bank::Bank, epoch_stakes::BLSPubkeyToRankMap},
  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `-D unused-imports` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(unused_imports)]`
```
CI seemed to have passed on #664, might have been an issue where the
branch was outdated.

#### Summary of Changes
Remove the unused import